# Generated by Django 5.0.6 on 2024-08-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوژی'), ('زبان برنامه نویسی', 'زبان برنامه نویسی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بلاگچین', 'بلاگچین'), ('سایر', 'سایر')], default='سایر', max_length=20),
        ),
    ]
